# Snapshot report for `test/log.js`

The actual snapshot is saved in `log.js.snap`.

Generated by [AVA](https://ava.li).

## [multipleResolves] should fire opts.log() with arguments

> Snapshot 1

    [
      `i  multipleResolves (a promise was  multiple times) ␊
      Initially resolved with: { success: true }␊
      Then rejected with: Error: message␊
          at STACK TRACE`,
      `MultipleResolves: a promise was resolved/rejected multiple times:␊
      Initially resolved with: { success: true }␊
      Then rejected with: Error: message␊
          at STACK TRACE`,
      `MultipleResolves: a promise was resolved/rejected multiple times:␊
      Initially resolved with: { success: true }␊
      Then rejected with: Error: message`,
      'info',
      `i  multipleResolves (a promise was resolved multiple times) ␊
      Initially resolved with: { success: true }␊
      Then resolved again with: { success: true }`,
      `MultipleResolves: a promise was resolved multiple times:␊
      Initially resolved with: { success: true }␊
      Then resolved again with: { success: true }␊
      `,
      `MultipleResolves: a promise was resolved multiple times:␊
      Initially resolved with: { success: true }␊
      Then resolved again with: { success: true }`,
      'info',
      `i  multipleResolves (a promise was  multiple times) ␊
      Initially rejected with: Error: message␊
      Then resolved with: { success: true }␊
          at STACK TRACE`,
      `MultipleResolves: a promise was resolved/rejected multiple times:␊
      Initially rejected with: Error: message␊
      Then resolved with: { success: true }␊
          at STACK TRACE`,
      `MultipleResolves: a promise was resolved/rejected multiple times:␊
      Initially rejected with: Error: message␊
      Then resolved with: { success: true }`,
      'info',
      `i  multipleResolves (a promise was rejected multiple times) ␊
      Initially rejected with: Error: message␊
      Then rejected again with: Error: message␊
          at STACK TRACE`,
      `MultipleResolves: a promise was rejected multiple times:␊
      Initially rejected with: Error: message␊
      Then rejected again with: Error: message␊
          at STACK TRACE`,
      `MultipleResolves: a promise was rejected multiple times:␊
      Initially rejected with: Error: message␊
      Then rejected again with: Error: message`,
      'info',
    ]

## [rejectionHandled] should fire opts.log() with arguments

> Snapshot 1

    [
      `×  rejectionHandled (a promise was rejected and handled too late)  Error: message␊
          at STACK TRACE`,
      `RejectionHandled: a promise was rejected and handled too late: Error: message␊
          at STACK TRACE`,
      'RejectionHandled: a promise was rejected and handled too late: Error: message',
      'error',
    ]

## [uncaughtException] should fire opts.log() with arguments

> Snapshot 1

    [
      `×  uncaughtException (an exception was thrown but not caught)  Error: message␊
          at STACK TRACE`,
      `UncaughtException: an exception was thrown but not caught: Error: message␊
          at STACK TRACE`,
      'UncaughtException: an exception was thrown but not caught: Error: message',
      'error',
    ]

## [unhandledRejection] should fire opts.log() with arguments

> Snapshot 1

    [
      `×  unhandledRejection (a promise was rejected but not handled)  Error: message␊
          at STACK TRACE`,
      `UnhandledRejection: a promise was rejected but not handled: Error: message␊
          at STACK TRACE`,
      'UnhandledRejection: a promise was rejected but not handled: Error: message',
      'error',
    ]

## [warning] should fire opts.log() with arguments

> Snapshot 1

    [
      `‼  warning (WarningType)  message␊
      [500] Detail␊
          at STACK TRACE`,
      `Warning: WarningType: message␊
      [500] Detail␊
          at STACK TRACE`,
      `Warning: WarningType: message␊
      [500] Detail`,
      'warn',
    ]
