# Snapshot report for `test/register.js`

The actual snapshot is saved in `register.js.snap`.

Generated by [AVA](https://ava.li).

## [multipleResolves] should work using both the -r flag and init()

> Snapshot 1

    {
      code: 0,
      stderr: '',
      stdout: '',
    }

## [multipleResolves] should work using the -r flag

> Snapshot 1

    {
      code: 0,
      stderr: '',
      stdout: `i  multipleResolves (a promise was  multiple times) ␊
      Initially resolved with: { success: true }␊
      Then rejected with: Error: message␊
          at STACK TRACE`,
    }

## [multipleResolves] should work with --no-warnings

> Snapshot 1

    {
      code: 0,
      stderr: '',
      stdout: `i  multipleResolves (a promise was  multiple times) ␊
      Initially resolved with: { success: true }␊
      Then rejected with: Error: message␊
          at STACK TRACE`,
    }

## [rejectionHandled] should work using both the -r flag and init()

> Snapshot 1

    {
      code: 0,
      stderr: '',
      stdout: '',
    }

## [rejectionHandled] should work using the -r flag

> Snapshot 1

    {
      code: 0,
      stderr: `×  unhandledRejection (a promise was rejected but not handled)  Error: message␊
          at STACK TRACE␊
       ×  rejectionHandled (a promise was rejected and handled too late)  Error: message␊
          at STACK TRACE`,
      stdout: '',
    }

## [rejectionHandled] should work with --no-warnings

> Snapshot 1

    {
      code: 0,
      stderr: `×  unhandledRejection (a promise was rejected but not handled)  Error: message␊
          at STACK TRACE␊
       ×  rejectionHandled (a promise was rejected and handled too late)  Error: message␊
          at STACK TRACE`,
      stdout: '',
    }

## [uncaughtException] should work using both the -r flag and init()

> Snapshot 1

    {
      code: 0,
      stderr: '',
      stdout: '',
    }

## [uncaughtException] should work using the -r flag

> Snapshot 1

    {
      code: 1,
      stderr: `×  uncaughtException (an exception was thrown but not caught)  Error: message␊
          at STACK TRACE`,
      stdout: '',
    }

## [uncaughtException] should work with --no-warnings

> Snapshot 1

    {
      code: 1,
      stderr: `×  uncaughtException (an exception was thrown but not caught)  Error: message␊
          at STACK TRACE`,
      stdout: '',
    }

## [unhandledRejection] should work using both the -r flag and init()

> Snapshot 1

    {
      code: 0,
      stderr: '',
      stdout: '',
    }

## [unhandledRejection] should work using the -r flag

> Snapshot 1

    {
      code: 0,
      stderr: `×  unhandledRejection (a promise was rejected but not handled)  Error: message␊
          at STACK TRACE`,
      stdout: '',
    }

## [unhandledRejection] should work with --no-warnings

> Snapshot 1

    {
      code: 0,
      stderr: `×  unhandledRejection (a promise was rejected but not handled)  Error: message␊
          at STACK TRACE`,
      stdout: '',
    }

## [warning] should work using both the -r flag and init()

> Snapshot 1

    {
      code: 0,
      stderr: '',
      stdout: '',
    }

## [warning] should work using the -r flag

> Snapshot 1

    {
      code: 0,
      stderr: `‼  warning (WarningType)  message␊
      [500] Detail␊
          at STACK TRACE`,
      stdout: '',
    }

## [warning] should work with --no-warnings

> Snapshot 1

    {
      code: 0,
      stderr: `‼  warning (WarningType)  message␊
      [500] Detail␊
          at STACK TRACE`,
      stdout: '',
    }
