# Snapshot report for `test/simple.js`

The actual snapshot is saved in `simple.js.snap`.

Generated by [AVA](https://ava.li).

## [multipleResolves] should work using both the -r flag and init()

> Snapshot 1

    {
      code: 0,
      message: '',
      stdout: '',
    }

## [multipleResolves] should work using the -r flag

> Snapshot 1

    {
      code: 0,
      message: '',
      stdout: `i  multipleResolves (a promise was resolved/rejected multiple times)  Initially resolved with: { success: true }␊
          Then rejected with: Error: message␊
              at STACK TRACE`,
    }

## [multipleResolves] should work with --no-warnings

> Snapshot 1

    {
      code: 0,
      message: '',
      stdout: `i  multipleResolves (a promise was resolved/rejected multiple times)  Initially resolved with: { success: true }␊
          Then rejected with: Error: message␊
              at STACK TRACE`,
    }

## [rejectionHandled] should work using both the -r flag and init()

> Snapshot 1

    {
      code: 0,
      message: '',
      stdout: '',
    }

## [rejectionHandled] should work using the -r flag

> Snapshot 1

    {
      code: 0,
      message: `×  unhandledRejection (a promise was rejected but not handled)  Error: message␊
              at STACK TRACE␊
       ×  rejectionHandled (a promise was rejected and handled too late)  Error: message␊
              at STACK TRACE`,
      stdout: '',
    }

## [rejectionHandled] should work with --no-warnings

> Snapshot 1

    {
      code: 0,
      message: `×  unhandledRejection (a promise was rejected but not handled)  Error: message␊
              at STACK TRACE␊
       ×  rejectionHandled (a promise was rejected and handled too late)  Error: message␊
              at STACK TRACE`,
      stdout: '',
    }

## [uncaughtException] should work using both the -r flag and init()

> Snapshot 1

    {
      code: 0,
      message: '',
      stdout: '',
    }

## [uncaughtException] should work using the -r flag

> Snapshot 1

    {
      code: 1,
      message: `×  uncaughtException (an exception was thrown but not caught)  Error: message␊
              at STACK TRACE`,
      stdout: '',
    }

## [uncaughtException] should work with --no-warnings

> Snapshot 1

    {
      code: 1,
      message: `×  uncaughtException (an exception was thrown but not caught)  Error: message␊
              at STACK TRACE`,
      stdout: '',
    }

## [unhandledRejection] should work using both the -r flag and init()

> Snapshot 1

    {
      code: 0,
      message: '',
      stdout: '',
    }

## [unhandledRejection] should work using the -r flag

> Snapshot 1

    {
      code: 0,
      message: `×  unhandledRejection (a promise was rejected but not handled)  Error: message␊
              at STACK TRACE`,
      stdout: '',
    }

## [unhandledRejection] should work with --no-warnings

> Snapshot 1

    {
      code: 0,
      message: `×  unhandledRejection (a promise was rejected but not handled)  Error: message␊
              at STACK TRACE`,
      stdout: '',
    }

## [warning] should work using both the -r flag and init()

> Snapshot 1

    {
      code: 0,
      message: '',
      stdout: '',
    }

## [warning] should work using the -r flag

> Snapshot 1

    {
      code: 0,
      message: `‼  warning  (500) Detail␊
          Error: message␊
              at STACK TRACE`,
      stdout: '',
    }

## [warning] should work with --no-warnings

> Snapshot 1

    {
      code: 0,
      message: `‼  warning  (500) Detail␊
          Error: message␊
              at STACK TRACE`,
      stdout: '',
    }
